# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=datetime.datetime(2016, 4, 24, 14, 15, 6, 758378, tzinfo=utc))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projs.Empregado')),
            ],
        ),
    ]
