# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 24, 14, 19, 50, 133545, tzinfo=utc)),
        ),
    ]
