# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='texto',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
