# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0002_auto_20160424_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
