# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0002_projecto_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('texto', models.TextField(default='', max_length=2000)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='projecto',
            name='data',
        ),
        migrations.RemoveField(
            model_name='projecto',
            name='texto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projs.Projecto'),
        ),
    ]
