# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0003_auto_20160424_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
