# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0003_auto_20160509_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='titulo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
