# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0004_blogpost_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitulo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
