# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0005_blogpost_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projs.Empregado'),
        ),
    ]
